services:
  - type: web
    name: nara-store
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_CALLBACK_URL
        sync: false
